import type { UserRepositoryPort } from '../core/application/ports/outbound';

/** UserRepositoryPort Mock 팩토리 */
export const createUserRepositoryMock = (): jest.Mocked<UserRepositoryPort> => ({
  findOneRecordByEmail: jest.fn(),
  findOneRecordById: jest.fn(),
  findRootByOrganizationId: jest.fn(),
  findManyRecordsByOrganizationId: jest.fn(),
  findManyWithdrawnRecordsByOrganizationId: jest.fn(),
  updateMemberStatusRecord: jest.fn(),
  purgeMemberRecord: jest.fn(),
  updateMemberDepartmentRecord: jest.fn(),
  updateMemberPositionRecord: jest.fn(),
  findTeamLeaderRecordByDepartment: jest.fn(),
  clearDepartmentForMembers: jest.fn(),
  createRecord: jest.fn(),
  updatePasswordHashRecord: jest.fn(),
  updateLoginSecurityRecord: jest.fn(),
  incrementTokenVersionRecord: jest.fn(),
  transferRootRecord: jest.fn(),
  replaceRootWithNewRecord: jest.fn(),
  updateEmailRecord: jest.fn(),
  updateProfileRecord: jest.fn(),
  findOrganizationById: jest.fn(),
  findOrganizationBySlug: jest.fn(),
  findManyOrganizationRecords: jest.fn(),
  createOrganizationRecord: jest.fn(),
  updateOrganizationRecord: jest.fn(),
  updateOrganizationStatusRecord: jest.fn(),
  bumpTokenVersionByOrganizationId: jest.fn(),
  purgeOrganizationRecord: jest.fn(),
  findOrganizationAiToolKeys: jest.fn(),
  setOrganizationAiToolsRecord: jest.fn(),
  findOrganizationAiToolsResolvedRecords: jest.fn(),
  listAiToolCatalogRecords: jest.fn(),
  findAiToolRecordByKey: jest.fn(),
  findAiToolRecordBySlug: jest.fn(),
  updateAiToolRecordByKey: jest.fn(),
  findPlatformAssistantSettingsRecord: jest.fn(),
  updatePlatformAssistantSettingsRecord: jest.fn(),
});
