"""add captions_file_id to video_jobs

Revision ID: a5ad1960b9cf
Revises: 0003_rename_video_jobs
Create Date: 2026-07-24 09:13:21.360052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ad1960b9cf'
down_revision: Union[str, None] = '0003_rename_video_jobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('captions_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'captions_file_id')
    # ### end Alembic commands ###
